version: '3.8'

services:
  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 4200:4200
    command:
      [
        "sh",
        "-c",
        "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"
      ]
    networks:
      - my-network

networks:
  my-network:
    ipam:
      driver: bridge